"""0007 create roleTable

Revision ID: 0ae62355b960
Revises: 6f86786d9d7f
Create Date: 2022-05-21 19:51:09.677769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ae62355b960'
down_revision = '6f86786d9d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('provider', sa.Column('unit_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('provider', sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'provider', 'units', ['unit_id'], ['id'])
    op.create_foreign_key(None, 'provider', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider', type_='foreignkey')
    op.drop_constraint(None, 'provider', type_='foreignkey')
    op.drop_column('provider', 'role_id')
    op.drop_column('provider', 'unit_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
