"""0007 edit ProviderTable 01

Revision ID: 2280fa680fa1
Revises: 637d3ed3664f
Create Date: 2022-05-22 01:48:33.852768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2280fa680fa1'
down_revision = '637d3ed3664f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provider_staff_id', table_name='provider')
    op.create_index(op.f('ix_provider_staff_id'), 'provider', ['staff_id'], unique=True)
    op.create_unique_constraint(None, 'provider', ['username'])
    op.create_unique_constraint(None, 'provider', ['email'])
    op.drop_column('provider', 'grants_appointments')
    op.drop_column('provider', 'nationality')
    op.drop_column('provider', 'specialist')
    op.drop_column('provider', 'is_consultant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('is_consultant', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('provider', sa.Column('specialist', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('provider', sa.Column('nationality', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.add_column('provider', sa.Column('grants_appointments', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'provider', type_='unique')
    op.drop_constraint(None, 'provider', type_='unique')
    op.drop_index(op.f('ix_provider_staff_id'), table_name='provider')
    op.create_index('ix_provider_staff_id', 'provider', ['staff_id'], unique=False)
    # ### end Alembic commands ###
