"""0005 provider_department table

Revision ID: 290aebea4f36
Revises: 3765f56c55c6
Create Date: 2022-05-09 01:46:47.775278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '290aebea4f36'
down_revision = '3765f56c55c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('provider',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('department_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('phone_number', sa.String(length=60), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('middle_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('dob', sa.String(length=60), nullable=False),
    sa.Column('gender', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('staff_id', sa.String(length=60), nullable=False),
    sa.Column('is_consultant', sa.Boolean(), nullable=True),
    sa.Column('specialist', sa.Boolean(), nullable=True),
    sa.Column('grants_appointments', sa.Boolean(), nullable=True),
    sa.Column('street_address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('nationality', sa.String(length=60), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_staff_id'), 'provider', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_staff_id'), table_name='provider')
    op.drop_table('provider')
    op.drop_table('departments')
    # ### end Alembic commands ###
