"""0004 Product Table modified

Revision ID: 3765f56c55c6
Revises: 6df6caf9fabf
Create Date: 2022-05-04 19:26:32.530392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3765f56c55c6'
down_revision = '6df6caf9fabf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('short_description', sa.String(length=500), nullable=True))
    op.add_column('product', sa.Column('description', sa.String(length=1500), nullable=True))
    op.add_column('product', sa.Column('date_added', sa.Date(), nullable=False))
    op.add_column('product', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('dimension', sa.String(length=20), nullable=True))
    op.drop_constraint('product_images_id_fkey', 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key('product_images_id_fkey', 'product_images', 'product', ['id'], ['id'])
    op.drop_column('product', 'dimension')
    op.drop_column('product', 'weight')
    op.drop_column('product', 'date_added')
    op.drop_column('product', 'description')
    op.drop_column('product', 'short_description')
    # ### end Alembic commands ###
