"""0001 Customer Profile Image Column

Revision ID: 590769300ef5
Revises: 9e4cea839778
Create Date: 2022-05-02 09:34:20.014565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590769300ef5'
down_revision = '9e4cea839778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('profile_image_url', sa.String(length=255), nullable=True))
    op.drop_constraint('customer_password_key', 'customer', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('customer_password_key', 'customer', ['password'])
    op.drop_column('customer', 'profile_image_url')
    # ### end Alembic commands ###
