"""0001 create_product_socials_productImage

Revision ID: 99a657bf442a
Revises: 
Create Date: 2022-05-04 17:26:03.054643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99a657bf442a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('seller_username', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('categories', sa.String(length=60), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['seller_username'], ['customer.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_accounts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('customer', sa.String(length=60), nullable=True),
    sa.Column('linkedin', sa.String(length=60), nullable=True),
    sa.Column('facebook', sa.String(length=60), nullable=True),
    sa.Column('twitter', sa.String(length=60), nullable=True),
    sa.Column('reddit', sa.String(length=60), nullable=True),
    sa.Column('quora', sa.String(length=60), nullable=True),
    sa.Column('telegram', sa.String(length=60), nullable=True),
    sa.Column('instagram', sa.String(length=60), nullable=True),
    sa.Column('wechat', sa.String(length=60), nullable=True),
    sa.Column('sina', sa.String(length=60), nullable=True),
    sa.Column('tiktok', sa.String(length=60), nullable=True),
    sa.Column('snapshot', sa.String(length=60), nullable=True),
    sa.Column('pin_interest', sa.String(length=60), nullable=True),
    sa.Column('discord', sa.String(length=60), nullable=True),
    sa.Column('signal', sa.String(length=60), nullable=True),
    sa.Column('skype', sa.String(length=60), nullable=True),
    sa.Column('line', sa.String(length=60), nullable=True),
    sa.Column('slack', sa.String(length=60), nullable=True),
    sa.Column('medium', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customer.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_images',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_image', sa.String(length=255), nullable=True),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_images')
    op.drop_table('social_accounts')
    op.drop_table('product')
    # ### end Alembic commands ###
