"""set customer username as foreign key

Revision ID: 9e4cea839778
Revises: 52885a9a9f18
Create Date: 2022-05-01 05:17:54.642322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4cea839778'
down_revision = '52885a9a9f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('username', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'address', 'customer', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'username')
    # ### end Alembic commands ###
