"""address circular imports

Revision ID: ba13241f4f6f
Revises: 69d5f83d9335
Create Date: 2022-05-01 04:57:31.409267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba13241f4f6f'
down_revision = '69d5f83d9335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('address_username_fkey', 'address', type_='foreignkey')
    op.drop_column('address', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('username', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.create_foreign_key('address_username_fkey', 'address', 'customer', ['username'], ['username'])
    # ### end Alembic commands ###
