"""0012 PatientTable registration name change

Revision ID: c0e55ca7bf63
Revises: f812cbdc4b47
Create Date: 2022-06-05 00:21:37.824026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0e55ca7bf63'
down_revision = 'f812cbdc4b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('registration', sa.String(length=60), nullable=False))
    op.drop_column('patients', 'registration_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('registration_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('patients', 'registration')
    # ### end Alembic commands ###
