import os

BASE_URL = os.getenv('BASE_URL')
SECRET_KEY = os.getenv('SECRET_KEY')
DATABASE_URL = os.getenv('DATABASE_URL')
CLOUDINARY_SECRET = os.getenv('CLOUDINARY_SECRET')
CLOUDINARY_NAME = os.getenv('CLOUDINARY_NAME')
CLOUDINARY_URL = os.getenv('CLOUDINARY_URL')
CLOUDINARY_KEY = os.getenv('CLOUDINARY_KEY')
IMAGEKIT_URL_ENDPOINT = os.getenv('IMAGEKIT_URL_ENDPOINT')
IMAGEKIT_CUSTOMER_PROFILE_BASEURL = os.getenv('IMAGEKIT_CUSTOMER_PROFILE_BASEURL')
IMAGEKIT_PUBLIC_KEY = os.getenv('IMAGEKIT_PUBLIC_KEY')
IMAGEKIT_PRIVATE_KEY = os.getenv('IMAGEKIT_PRIVATE_KEY')