BASE_URL = '/api/v1/zhik/store/commerce/'
SECRET_KEY = 'OLIxKOeueM-pIpOABjnBL-OvNN2Md8lB-TlKeHHJKUj-mQVlbMVT2T-0WORlcJGdu-mgZFCjrpEb-FlbKG9mIKm-nuMIBqjSup-UiFSQeavIx'
DATABASE_URL = 'postgresql://postgres:postgres@localhost:5432/zhik-store'
# DATABASE_URL = 'postgres://vkligerp:sWYam4V9euVH_VXuOlLlrcaJvtVLC2za@manny.db.elephantsql.com/vkligerp'
DEFAULT_PROFILE_IMG = 'https://ik.imagekit.io/zalajobi/zhik-store/default_profile_pic_y4-z9eBo7.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1651485516772'